### ISSUE TITLE
Assess fairness w/respect to gender (milestone outline)

### ISSUE THREAD

**Issue by AlexOlza** [AlexOlza/estratificacion#60]
- [x] Build separate models for each sex. Expected code modifications:
      - [ ] new experiment, same algorithms. Include new attribute in config file(s?). kwarg gender in getData (if config hasattr...)
- [x] Report the results of current models amongst sex subgroups separately. The code modifications above should suffice.
- [ ]Decide which fairness metrics we want to analyze
- [ ] Inspect the python libraries listed in the article "Algorithmic Fairness in Computational Medicine"
- [ ] If needed, implement fairness metrics in python
