### ISSUE TITLE
Hyperparameter variability 

### ISSUE THREAD

**Issue by AlexOlza** [AlexOlza/estratificacion#61]
For hyperparameter tuning of the ensemble models, we define a hyperparameter space and train 50 models at random within that space. Those 50 models (i.e. the subspace) are evaluated with cross-validation, and we select the one with the highest **accuracy**.

The chosen subspace depends on the random seed. Therefore, the final model does too. 

**TASK:** Vary the random seed to explore different subspaces, obtaining a set of "final models". Analyze the distribution of the metrics of interest. 

**Expected code:** 

- [x] A new experiment file, that receives the seed via sys args - Check out argparse module
- [x] Modify the algorithms and the main programs to use this seed
- [x] Modify the main programs to accept the model name via argparse. The name will include the random seed used.
- [x] Analysis tools: plots and tables of the distribution of metrics, and maybe histograms of the selected hyperparameters

**Comment by AlexOlza** [comment]
We need two different seeds for undersamplling and hyperparameter tuning!!!
